apiVersion: v1
kind: ServiceAccount
metadata:
  name:  default
  namespace: shield
---
apiVersion: v1
kind: Service
metadata:
  name: the-bus
  namespace: shield
spec:
  type: NodePort
  selector:
    env: marvel
  ports:
  - nodePort: 31112
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  namespace: shield
  name: triskelion
  labels:
    env: marvel
spec:
  containers:
  - image: nigelpoulton/k8sbook:shield-01
    name: bus-ctr
    ports:
    - containerPort: 8080
    imagePullPolicy: Always
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
