apiVersion: v1
kind: Pod
metadata:
  name: git-sync
  labels:
    name: sidecar
spec:
  containers:
  - name: ctr-web
    image: nginx
    volumeMounts:
      - mountPath: /usr/share/nginx/
        name: html
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: ctrl-sync
    image: k8s.gcr.io/git-sync:v3.1.6
    volumeMounts:
      - mountPath: /tmp/git
        name: html
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
    - name: GIT_SYNC_REPO
      value: https://github.com/gu4ripolo/ps-sidecar.git
    - name: GIT_SYNC_BRANCH
      value: master
    - name: GIT_SYNC_DEPTH
      value: "1"
    - name: GIT_SYNC_DEST
      value: "html"
  volumes:
  - name: html
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: svc-sidecar
spec:
  selector:
    app: sidecar
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001